### PR TITLE
added exported function rerenderAddedDataCampExercises for #21

### PR DESCRIPTION
**Pull request by HannesBuseyne**
function requested in issue 21

### CODE REVIEW

**Comment by EvertEt** [comment]
@HannesBuseyne You could just move the following code outside of the function and export that function (or put in in a parent function) so this code is not duplicated.
`     checkPoweredBy();
      loadScriptAsync(DCL_URL + '{{scriptLink}}');
`
You can also remove the `dclLoaded ` variable now you export something else.

**Comment by HannesBuseyne** [comment]
I just called the exported function instead of the duplication if that's ok. Also changed the allreadyExecuted function

**Comment by EvertEt** [comment]
I'm not sure if there are any drawbacks but I would call the local version instead of the window version. (I've changed it locally, testing and i'll push).
Would you mind also adding this function to the readme?

**Comment by EvertEt** [comment]
@HannesBuseyne I had forgotten you would also need to bootstrap the new exercises for angular to kick in. I've done so in b3199d2.

**Comment by HannesBuseyne** [comment]
@EvertEt : yeah, sorry. Tried to test it locally before commiting but always got this error when trying to load the exercises :
image
(even when just changing the DCL_URL)

**Comment by EvertEt** [comment]
@HannesBuseyne I think the problem is the `https` in `DCL_URL`, could you try changing it to `http`?

**Comment by HannesBuseyne** [comment]
@EvertEt :yep, solved it. Sorry, stupid mistake -_-

**Comment by HannesBuseyne** [comment]
Just tested locally and seems to work fine now, thanks :)

**Comment by ludov04** [comment]
@EvertEt Is this mergeable ?

**Comment by EvertEt** [comment]
@ludov04 If it has been tested, yes. Looks good.

**Pull request merged**
